In [1]:
# import relevant libraries
import pandas as pd
import numpy as np

# Fundamental Built-in Python Functions for Data Science

## - python print() function

- takes in data as input

- prints output

In [2]:
## Create variable with text
greeting = 'Hello, my name is John'

In [3]:
## Use print function on variable to print text
print(greeting)

Hello, my name is John


In [4]:
## Create greeting variables
greet1 = "Hello"
greet2 = 'Hey'

## Create name variables
name1 = 'John'
name2 = 'Jareth'

## Create puncation variable
punctuation = '!'

In [5]:
## Use print function to assemble sentences out of variables
### Seperate variables with commas in between
print(greet1, name1, punctuation)

print(greet2, name2, punctuation)

Hello John !
Hey Jareth !


In [6]:
## Create list of odd numbers
odd_numbers = [-5, -3, -1, 1, 3, 5]

In [7]:
## Use print function to display list
print(odd_numbers)

[-5, -3, -1, 1, 3, 5]


In [8]:
## Create tuples indicating points on a line
(x1, y1) = (5, 6)

(x2, y2) = (-7, -8)

In [9]:
## Use print to display the result of a math equation
print('Slope:', (y2 - y1) / (x2 - x1))

Slope: 1.1666666666666667


In [10]:
# read grades dataset & save as a pandas dataframe
grades = pd.read_csv('grades.csv')

In [11]:
# fill missing grades with zeros
grades['grade'] = grades['grade'].fillna(0)

In [12]:
grades.head()

exam  student_id  grade
0     1           1   86.0
1     1           2   65.0
2     1           3   70.0
3     1           4   98.0
4     1           5   89.0

In [13]:
## Create subset of students with grades higher than 70
passing = grades.loc[grades['grade'] >= 70]['grade'].values

## Create subset of students with grades lower than 70
failing = grades.loc[grades['grade'] < 70]['grade'].values

In [14]:
## Use print function to display data in subsets
print('grades atleast 70%:', passing)

print('grades below 70%:', failing)

grades atleast 70%: [ 86.  70.  98.  89.  75.  90.  81.  79.  78.  75.  80.  87.  82.  95.
  96.  78.  80.  87.  89.  90. 100.  72.  73.  75.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  90.  91.  92.  93.  94.  95.  96.  97.  98.]
grades below 70%: [65.  0. 56. 60.  0.  0.  0.  0.]


## - python input() function

- takes a prompt 

- displays prompt to user

- allows user to respond to prompt

- returns the user's response as a string

In [15]:
## Create a variable that prompts the user to enter their name
name = input('Please enter your name: ')

Please enter your name:  John


In [16]:
## Create a response to display to the user
print('Nice to meet you, ', name)

Nice to meet you,  John


In [17]:
# compute mean grade for Exam #1 & save in variable
exam1_mean = grades.loc[grades['exam'] == 1]['grade'].mean()
exam1_mean

71.0

In [18]:
## Create a prompt to ask a student what their grade was on exam #1
grade = input('Please enter your grade for Exam #1: ')

Please enter your grade for Exam #1:  92


In [19]:
## Create a variable that computes the difference between the grade the the exam #1 avg
diff = int(grade) - exam1_mean

diff

21.0

In [20]:
## Create an appropriate response depending on if the grade was higher or lower than the avg
if diff > 0:
    print('You scored', diff, 'points higher than the mean', exam1_mean)
elif diff < 0:
    print('You scored', diff, 'points lower than the mean', exam1_mean)
else:
    print('You scored the same as the mean', exam1_mean)

You scored 21.0 points higher than the mean 71.0


## - python abs() function

- takes a numerical value as input

- returns absolute value of the number

In [21]:
## Use abs function to print the absolute value of a number
abs(70)

70

In [22]:
## Use the abs function to print the absolute value of a negative number
abs(-65)

65

In [23]:
## Create a variable indicating a temperature
temp1 = 98.2

In [24]:
## Use abs function to find absolute value of temperature
abs(temp1)

98.2

In [25]:
## Create a 2nd variable of a temperature on a freezing day
temp2 = -12.5

In [26]:
## Use abs function to display absolute value of a negative temperature
abs(temp2)

12.5

In [27]:
## Create tuples indicating points on a graph
(x1, y1) = (12, 34)

(x2, y2) = (-4, 17)

In [28]:
# compute manhattan distance between the two points
abs(x1 - x2) + abs(y1 - y2)

33

## - python round() function

- will take in a numerical value as input

- will take in a second number to indicate how many digits after the decimal to round to
    - if no second number is specified it will round to the closest whole number


- if equally distanced between 2 numbers, it will round to the even integer

In [29]:
## Use round function on a decimal
round(-12.213)

-12

In [30]:
## Use round function on the same number, but pass in a second argument
round(-12.213, 2)

-12.21

## - python min() function

- takes in either a sequence of numbers or a list of items as input

- if given a sequence it will return the smallest number in the sequence

- if given a list it will return the smallest item on the list

In [31]:
## Initialize nums as a tuple containing some integers
nums = (5, -2, 7, -1, 9, 0)

In [32]:
## Use min function to find the smallest integer
min(nums)

-2

In [33]:
## Initialize listF as a list containing some floating-point numbers
listF = [1.2, -6.17, -9.53, 5.8, -6.7]

In [34]:
## Use min function to find the smallest item in the list
min(listF)

-9.53

In [35]:
# Min function can be used directly on a series of numbers
min(3.84, 3.48, 3.8, 3.004, 3.4)

3.004

## - python max() function

- takes in either a sequence of numbers or a list of items as input

- if given a sequence it will return the largest number in the sequence

- if given a list it will return the largest item on the list

In [36]:
## Use max function to find the largest number
max(nums)

9

In [37]:
## Use max function to find the largest item in the list
max(listF)

5.8

In [38]:
# Max function can be used directly on a series of numbers
max(3.84, 3.48, 3.8, 3.004, 3.4)

3.84

## - python sorted() function

- takes in a sequence as data

- returns the sequence as a sorted list

- does not actually modify original list

- can take in a second argument known as reverse
    - reverse can be set to True or False
    - default is False indicating the order will be ascending
    - if set to True the order displayed will be descending

In [39]:
## Create a list of names
names = {'Alondra', 'Spencer', 'Elizabeth', 'Eddie', 'Henrietta'}

In [40]:
## Create a new list of the names listed alphabetically
alphabetical_names = sorted(names)

alphabetical_names

['Alondra', 'Eddie', 'Elizabeth', 'Henrietta', 'Spencer']

In [41]:
## names was not changed
names

{'Alondra', 'Eddie', 'Elizabeth', 'Henrietta', 'Spencer'}

In [42]:
## Create a list of names listed backwards alphabetically
backwards_names = sorted(names, reverse = True)

backwards_names

['Spencer', 'Henrietta', 'Elizabeth', 'Eddie', 'Alondra']

In [43]:
## Create a tuple of numbers 
nums = (5, -2, 7, -1, 9, 0)

In [44]:
## Create a new list of the numbers sorted from smallest to largest
ordered_nums = sorted(nums)
ordered_nums

[-2, -1, 0, 5, 7, 9]

In [45]:
## Create a new list of the numbers sorted from largest to smallest
backwards_nums = sorted(nums, reverse = True)
backwards_nums

[9, 7, 5, 0, -1, -2]

In [46]:
# Create a list of some float numbers
listF = [1.2, -6.17, -9.53, 5.8, -6.7]

In [47]:
## Create a new list of the floats sorted from smallest to largest
ordered_floats = sorted(listF)
ordered_floats

[-9.53, -6.7, -6.17, 1.2, 5.8]

In [48]:
## Create a new list of the floats sorted from largest to smalles
backwards_floats = sorted(listF, reverse = True)
backwards_floats

[5.8, 1.2, -6.17, -6.7, -9.53]

## - python sum function

- takes a sequence of numbers as input

- returns the sum of all the numbers in the sequence

In [49]:
## Use sum function to compute the sum of all numbers in nums
sum(nums)

18

In [50]:
## Create a list containing some integers
listN = [212, 305, -736, -801, 999]

In [51]:
## Use sum function to compute sum of items in a list
sum(listN)

-21

## - python len function

- takes in either a sequence or a collection of items as input

- returns an integer indicating how long the list is

In [52]:
## Use len function to display the length of a list
len(listF)

5

In [53]:
## Use len function to display the length of a tuple
len(nums)

6

In [54]:
## Use len function to display the length of a set
len(names)

5

In [55]:
## Create  a dictionary containing key-value pairs that map day to activity
exercise = {'Monday': 'Bike', 'Tuesday': 'Run', 'Wednesday': 'Swim', 'Thursday': 'Dance', 
            'Friday': 'Lift', 'Saturday': 'Martial Arts', 'Sunday': 'Basketball'}

In [56]:
## Use len function to display the length of a dictionary
len(exercise)

7

In [57]:
## Create a string as a variable
name1 = 'Keerthanadevi'

In [58]:
## Use len function to display the length of an object
len(name1)

13

## - python type() function

- takes an object as input

- returns what the data type of the object is

In [59]:
## Use type function to find the data type of a list
type(listF)

list

In [60]:
## Use type function to find the data type of a tuple
type(nums)

tuple

In [61]:
## Use type function to find the data type of a set
type(names)

set

In [62]:
## Use type function to find the data type of a dictionary
type(exercise)

dict

In [63]:
## Use type function to find the data type of a string
type(name1)

str

In [64]:
## Create a boolean variable
losing = False

In [65]:
## Use type function to find the data type of a boolean value
type(losing)

bool

In [66]:
## Create a numerical variable
players = 4

In [67]:
## Use type function to find the data type of a numerical value
type(players)

int

In [68]:
## Use type function to find the data type of a float
type(temp1)

float

# Advanced Built-in Python Functions for Data Science

## - python map() function

- takes in a function and a sequence of items

- apples the function to every item in the sequence

In [69]:
## Create a function
def lowest_grade(student_id):
    
    """Find lowest grade across all exams for student with given student_id.
    Treat missing exam grades as zeros."""
    
    return grades.loc[grades['student_id'] == student_id]['grade'].fillna(0).min()

In [70]:
## Create a sequence containing all distinct student ids
student_ids = grades['student_id'].unique()
student_ids

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
## Use map function to apply your function to every item in a sequence
list(map(lowest_grade, student_ids))

[0.0, 0.0, 70.0, 0.0, 0.0, 0.0, 75.0, 56.0, 73.0, 75.0]

## - python zip() function

- takes in 2 or more sequences as input

- allows you to iterate through multiple sequences simultaneously 

In [72]:
## Create a list of scores
points_game1 = [50, 40, 60, 70, 80]

## Create a second list of scores
points_game2 = [76, 81, 53, 92, 67]

In [73]:
## Create an empty sequence to store results
diffs = []

In [74]:
## Use zip function to iterate through both lists at the same time
for x, y in zip(points_game1, points_game2):
    # Compute absolute value of difference between game 1 and game 2
    # append to diff
    diffs.append(abs(x - y))
    
diffs

[26, 41, 7, 22, 13]

## - python filter() function

- takes in a function and a sequence as input

- iterates through the sequence using the terms outlined in the functions

- returns a squence of the items where the function's terms were True

In [75]:
## Create a function that will return a bool value
def mean_atleast_70(student_id):
    
    """Compute mean grade across all exams for student with given student_id.
    Treat missing exam grades as zeros.
    If mean grade is atleast 70, return True. Otherwise, return False."""
    
    mean_grade = grades.loc[grades['student_id'] == student_id]['grade'].fillna(0).mean()
    return mean_grade >= 70

In [76]:
## Use filter funtion to iterate through list of students to see which satisfy the condition of the function
list(filter(mean_atleast_70, student_ids))

[3, 5, 7, 8, 9, 10]

# Functions from the Numpy Library for Manipulation of Numerical Data

In [77]:
## Import relevant libraries
import numpy as np

## - Create Numpy Arrays in Python

#### - Numpy's array() function 

- a grid like data structure containing multiple values of the same data type

- 1 dimensional arrays are called a vector

- multi dimensional arrays are called matrices

In [78]:
## Use numpy's array function to create an empty array variable
array0 = np.array([])
array0

array([], dtype=float64)

In [79]:
## Create a list of numbers
list1 = [1, 2, 3, 4, 5, 6]

In [80]:
## Use numpy's array function to convert the list into a 1 dimensional array
array1 = np.array(list1)
array1

array([1, 2, 3, 4, 5, 6])

In [81]:
## Create a list of lists of numbers
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [82]:
## Use numpy's array function to convert a list of lists into a multidimensional array
array2 = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### - Numpy's arange() function

- allows you to create an array from a list only using items you specify

- takes in a start, stop, and step

- start is optional, if not specified the default is 0, or the beginning

- stop is required, to indicate the end of the interval, everything after the stop is unincluded

- step is optional, if not specified the default is 1, indicating the spacing between intervals

In [83]:
## Use numpy's arange function to create an array of numbers between 0 and 4
np.arange(5)

array([0, 1, 2, 3, 4])

In [84]:
## Use numpy's arange function to create an array of all even numbers between 0 and 10
np. arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

#### - Numpy's zeros() function

- takes in a specified shape and returns an array of all 0's

- specified shape can be either an integer or a tuple
    - if shape is an integer the returned array will be 1 dimensional
    - if shape is a tuple the returned array will be multi dimensional
        - first item is number of rows
        - second item is number of columns

In [85]:
## Use numpy's zeros function to create a 1 dimensional array of 5 0's
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [86]:
## Use numpy's zeros function to create a multi dimensional array of 4 rows and 5 columns of 0's
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### - Numpy's ones() function

- takes in a specified shape and returns an array of all 1's

- specified shape can be either an integer or a tuple
    - if shape is an integer the returned array will be 1 dimensional
    - if shape is a tuple the returned array will be multi dimensional
        - first item is number of rows
        - second item is number of columns

In [87]:
## Use numpy's ones function to create a 1 dimensional array of 6 1's
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [88]:
## Use numpy's ones function to create a multi dimensional array of 4 rows and 6 columns of 1's
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### - Numpy's linspace() function

- takes in 3 numerical inputs: start, stop, num

- start indicates start of the interval

- stop is required, indicating end of the interval

- both start and stop are included in the interval

- num indicates how many numbers to generate

- returns an array of that many evenly spaced numbers between start and stop

In [89]:
## Use numpy's linspace function to create a 1 dimensional array of 9 evenly spaced numbers between 1 and 2
np.linspace(1, 2, 9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

#### - Numpy's random.randint() function

- takes in 3 inputs: low, high, size

- returns an array of random integers

- low indicates the lowest value integer allowed, can be included

- high indicates the highest value integer allowed, will not be included

- size indicates how many integers total will be included

In [90]:
## Use numpy's random.randint function to make an array of 10 random integers between 20 and 50
np.random.randint(20, 50, 10)

array([24, 48, 44, 47, 38, 40, 40, 35, 41, 34])

## - Minimum and MAximum Values in NumPy Arrays

In [91]:
## Create a numpy array of 20 random integers from 1 to 50 & save in a variable
array_random = np.random.randint(1, 50, 20)
array_random

array([ 9,  4, 17, 45, 21,  5, 23, 17,  7,  9, 40, 11, 15,  8, 46,  6, 45,
       24, 15, 14])

In [92]:
## Use numpy's min function to find the lowest value in the array
np.min(array_random)

4

In [93]:
## Use numpy's max function to find the highest value in the array
np.max(array_random)

46

## - Indices of Minimun and MAximum Values in NumPy Arrays

In [94]:
## Use numpy's argmin function to find the location of the lowest value in the array
array_random.argmin()

1

In [95]:
## Use numpy's argmax function to find the location of the highest value in the array
array_random.argmax()

14

## - Find Shapes of NumPy Arrays and Reshape

In [96]:
## Use numpy's shape function to display the shape of an empty array
array0.shape

(0,)

In [97]:
## Use numpy's shape function to display the shape of a 1 dimensional array
array1.shape

(6,)

In [98]:
## Use numpy's shape function to display the shape of a multi dimensional array
array2.shape

(3, 3)

In [99]:
## Use numpy's shape function to display the shape of an array of zeros
zero_array = np.zeros((4, 5))
zero_array.shape

(4, 5)

In [100]:
## Use numpy's shape function to display the shape of an array of ones
one_array = np.ones((3, 6))
one_array.shape

(3, 6)

In [101]:
## Use numpy's shape function to display the shape of an array of random integers
array_random.shape

(20,)

In [102]:
## Use numpy's reshape function to convert a 1 dimensional array into a multi dimenstional array
array_random1 = array_random.reshape(4, 5)
array_random1

array([[ 9,  4, 17, 45, 21],
       [ 5, 23, 17,  7,  9],
       [40, 11, 15,  8, 46],
       [ 6, 45, 24, 15, 14]])

In [103]:
## Use numpy's reshape function to convert a multi dimensional array into a differenct shape
array_random1.reshape(2, 10)

array([[ 9,  4, 17, 45, 21,  5, 23, 17,  7,  9],
       [40, 11, 15,  8, 46,  6, 45, 24, 15, 14]])

In [104]:
## Note array_random1 was not modified
array_random1

array([[ 9,  4, 17, 45, 21],
       [ 5, 23, 17,  7,  9],
       [40, 11, 15,  8, 46],
       [ 6, 45, 24, 15, 14]])

In [105]:
## Find the shape of the new array
array_random1.shape

(4, 5)

## - Select Items or Groups of Iems from NumPy Arrays

In [106]:
## Use brackets to select the first item of an array
array1[0]

1

In [107]:
## Select the first 3 items of an array
array1[0:3]

array([1, 2, 3])

In [108]:
## Select three items from an array starting at the second item
array1[1:4]

array([2, 3, 4])

In [109]:
## Select all items between the 3rd item and the last item of an array
array1[2:]

array([3, 4, 5, 6])

In [110]:
## Select the first item of a multi dimensional array
array2[0][0]

1

In [111]:
array2[0, 0]

1

In [112]:
## Select the item in row 1 column 2 of a multi dimensional array
array2[1, 2]

6

In [113]:
## Select the first 2 items of the first row
array2[:1, :2]

array([[1, 2]])

In [114]:
## Select the first 2 items of the first 2 rows
array2[:2, :2]

array([[1, 2],
       [4, 5]])

In [115]:
## Select the first 2 items of all rows
array2[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [116]:
## Select all items in the first row
array2[0]

array([1, 2, 3])

In [117]:
## Select all items in the second row
array2[1]

array([4, 5, 6])

In [118]:
## Select all items from an array that meet a specified condition
array_random[array_random > 25]

array([45, 40, 46, 45])

In [119]:
## Select all items from an array that meet 2 specified conditions
array_random[(array_random > 25) & (array_random <= 40)]

array([40])

## - Arithmatic Operations on NumPy Arrays

- all operations must be done between arrays that are the exact same shape

In [120]:
## Create an array of odd numbers between 1 and 20
arrayA = np.arange(1, 21, 2)
arrayA

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [121]:
## Create an array of numbers between 1 and 10
arrayB = np.arange(1, 11)
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
## Add the items of arrayA and arrayB
arrayA + arrayB

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [123]:
## Subtract the items of arrayA by the items in arrayB
arrayA - arrayB

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
## Multiply the items of arrayA and arrayB
arrayA * arrayB

array([  1,   6,  15,  28,  45,  66,  91, 120, 153, 190])

In [125]:
## Divide the items of arrayA by the items in arrayB
arrayA / arrayB

array([1.        , 1.5       , 1.66666667, 1.75      , 1.8       ,
       1.83333333, 1.85714286, 1.875     , 1.88888889, 1.9       ])

In [126]:
## Create a multi dimensional array
arrayC = np.array([[1, 2, 3], [4, 5, 6]])
arrayC

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
## Create a second multi dimensional array
arrayD = np.array([[7, 8, 9], [10, 11, 12]])
arrayD

array([[ 7,  8,  9],
       [10, 11, 12]])

In [128]:
## Add the items of arrayC and arrayD
arrayC + arrayD

array([[ 8, 10, 12],
       [14, 16, 18]])

In [129]:
## Subtract the items of arrayC by the items in arrayD
arrayC - arrayD

array([[-6, -6, -6],
       [-6, -6, -6]])

In [130]:
## Multiply the items of arrayC and arrayD
arrayC * arrayD

array([[ 7, 16, 27],
       [40, 55, 72]])

In [131]:
## Divide the items of arrayC by the items in arrayD
arrayC / arrayD

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

## - Scalar Operations on NumPy Arrays

In [132]:
## Add 3 to each item in arrayA
arrayA + 3

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [133]:
## Subtract 4 from each item in arrayA
arrayA - 4

array([-3, -1,  1,  3,  5,  7,  9, 11, 13, 15])

In [134]:
## Multiply each item in arrayA by 5
arrayA * 5

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [135]:
## Divide each item in arrayA by 2
arrayA / 2

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [136]:
## Add 3 to each item in arrayC
arrayC + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [137]:
## Subtract 4 from each item in arrayC
arrayC - 4

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [138]:
## Multiply each item in arrayC by 5
arrayC * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [139]:
## Divide each item in arrayC by 2
arrayC / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

## - Statistical Operations on NumPy Arrays

In [141]:
## Find the median of an array of random integers
np.median(array_random)

15.0

In [142]:
## Find the mean of an array of random integers
np.mean(array_random)

19.05

In [143]:
## Find the variance of an array of random integers
np.var(array_random)

187.54749999999999

In [144]:
## Find the standard deviation of an array of random integers
np.std(array_random)

13.694798282559695

## - Other Operations for NumPy Arrays